SistemPenjadwalan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import viewsBatchProduction

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls','users')),
    path('liniProduksi/', include('liniProduksi.urls','liniProduksi')),
    path('produk/', include('produk.urls','produk')),
    path('jadwal/', include('jadwal.urls','jadwal')),
    path('engineeringOrder/', include('engineeringOrder.urls','engineeringOrder')),
    path('contributor/',views.contributor, name='contributor'),
    path('home/',views.home, name='home'),
    path('', views.index, name='index'),
    path('batch/about/', viewsBatchProduction.about, name='about'),
    path('batch/about/&', viewsBatchProduction.dz, name='dz'),
    path('login/', viewsBatchProduction.loginview, name='login'),
    path('logout/', viewsBatchProduction.logoutview, name='logout'),
    path('plant/', viewsBatchProduction.plant, name='plant'),
    path('batch/', include('BatchProduction.urls'), name='batch'),
    path('<slug:instance>/', viewsBatchProduction.notfound, name='404'),
    # path('', viewsBatchProduction.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engineeringOrder/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'engineeringOrder'

urlpatterns = [
    path('tidakDisetujui/', views.tidakDisetujui, name='tidakDisetujui'),
    path('disetujui/', views.disetujui, name='disetujui'),
    path('belumDisetujui/', views.belumDisetujui, name='belumDisetujui'),
    path('tidakSetujuEngineeringOrder/<str:tidakSetuju_id>', views.tidakSetuju, name='tidakSetujuEO'),
    path('setujuEngineeringOrder/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaBerlakuEO/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaTidakBerlakuEO/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaBerlakuEO/<str:setuju_id>', views.prosesLamaBerlakuEO, name='prosesLamaBerlakuEO'),
    path('setujuEngineeringOrder/prosesLamaTidakBerlakuEO/<str:setuju_id>', views.prosesLamaTidakBerlakuEO, name='prosesLamaTidakBerlakuEO'),
    path('setujuEngineeringOrder/prosesBerlakuEO/<str:setuju_id>', views.prosesBerlakuEO, name='prosesBerlakuEO'),
    path('setujuEngineeringOrder/prosesLamaEO/<str:setuju_id>', views.prosesLamaEO, name='prosesLamaEO'),
    path('setujuEngineeringOrder/prosesEO/<str:setuju_id>', views.prosesEO, name='prosesEO'),
    path('setujuEngineeringOrder/<str:setuju_id>', views.setuju, name='setujuEO'),
    path('deleteEngineeringOrder/<str:delete_id>', views.deleteEO, name='deleteEO'),
    path('newEngineeringOrder/', views.newEO, name='newEO'),
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from . import views
app_name = 'users'

urlpatterns = [
    path('', views.registerView, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

engineeringOrder/models.py
from django.db import models
from produk.models import Material

# Create your models here.
class EngineeringOrder(models.Model):
    material = models.OneToOneField('produk.Material', on_delete=models.CASCADE, related_name='eo')
    idEO = models.CharField(max_length=255, unique=True)
    namaPengusul = models.CharField(max_length=255,)
    departemenPengusul = models.CharField(max_length=255,)
    keterangan = models.TextField()
    tanggalPengajuan = models.DateField()

    is_disetujui = models.BooleanField(null=True, blank=True)
    tanggalPersetujuan = models.DateField(null=True, blank=True)
    tanggalPerubahanBerlaku = models.DateField(null=True, blank=True)

    is_prosesBaru = models.BooleanField(null=True, blank=True)

    def save(self, *args, **kwargs):
        super(EngineeringOrder, self).save(*args, **kwargs)

    def __str__(self):
        return "{}".format(self.idEO)

engineeringOrder/forms.py
from django import forms
from .models  import EngineeringOrder
from produk.models import Material
from django.db.models import Q

class EOForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EOForm, self).__init__(*args, **kwargs)
        self.fields['material'].queryset = Material.objects.filter(is_berlaku=True).filter(Q(eo=self.instance))
        self.fields['material'].label_from_instance = lambda obj: "%s || Varian: %s || Penyusun produk: %s || Supplier: %s" % (obj.idMaterial, obj.varian, obj.penyusunProduk, obj.namaSupplier)

    class Meta:
        model = EngineeringOrder
        fields = [
            'material',
            'idEO',
            'namaPengusul',
            'departemenPengusul',
            'keterangan',
        ]

        labels = {
            'material':'Material yang Diajukan untuk Ganti',
            'idEO':'ID Engineering Order',
            'namaPengusul': 'Nama Lengkap Pengusul',
            'departemenPengusul': 'Departemen Pengusul',
            'keterangan': 'Alasan',
        }
        widgets = {
            'idEO': forms.TextInput(
                attrs = {
                    'class':'form-control',
                    'placeholder':'Masukkan id engineering order',
                }
            ),
            'namaPengusul': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Masukkan nama lengkap pengusul',
                }
            ),
            'departemenPengusul': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Masukkan departemen pengusul',
                }
            ),
            'keterangan': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Masukkan alasan mengganti material',
                }
            ),
        }

class PersetujuanEOForm(forms.ModelForm):
    class Meta:
        model = EngineeringOrder
        fields = [
            'tanggalPerubahanBerlaku',
        ]

        labels = {
            'tanggalPerubahanBerlaku': 'Tanggal Perubahan Mulai Berlaku',
        }
        widgets = {
            'tanggalPerubahanBerlaku': forms.TimeInput(
                attrs={
                    'type': 'date',
                }
            ),
        }

engineeringOrder/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
import datetime

from .models import EngineeringOrder
from .forms import EOForm, PersetujuanEOForm
from produk.models import Material, Varian
from produk.forms import MaterialPenggantiForm
from liniProduksi.models import KebutuhanMaterial, Proses, StasiunKerja, PengirimanMaterial
from liniProduksi.forms import ProsesGantiForm


def index(request):
    eo = EngineeringOrder.objects.all().order_by('-tanggalPengajuan')
    mat = Material.objects.all()
    context = {
        'Judul': 'Engineering Order',
        'eo': eo,
        'mat': mat,
    }
    return render(request, 'engineeringOrder/indexV2.html', context)

def newEO(request):
    eo_form = EOForm(request.POST or None)
    material_form = MaterialPenggantiForm(request.POST or None)

    # masukin data dari form ke database
    if request.method == 'POST':
        eo_form.id = request.POST.get('id')
        eo_form.material = request.POST.get('material')
        eo_form.idEO = request.POST.get('idEO')
        eo_form.namaPengusul = request.POST.get('namaPengusul')
        eo_form.departemenPengusul = request.POST.get('departemenPengusul')
        eo_form.keterangan = request.POST.get('keterangan')

        mt = Material.objects.get(id=eo_form.material)
        eo_form.tanggalPengajuan = datetime.datetime.now().date()
        EngineeringOrder.objects.create(id=eo_form.id,material=mt, idEO=eo_form.idEO, namaPengusul=eo_form.namaPengusul,
                                        departemenPengusul=eo_form.departemenPengusul, keterangan=eo_form.keterangan,
                                        tanggalPengajuan=eo_form.tanggalPengajuan)

        material_form.varian = request.POST.get('varian')
        get_varian = Varian.objects.get(idVarian=material_form.varian)
        material_form.id = request.POST.get('id')
        material_form.idMaterial = request.POST.get('idMaterial')
        material_form.namaMaterial = request.POST.get('namaMaterial')
        material_form.namaSupplier = request.POST.get('namaSupplier')
        material_form.penyusunProduk = request.POST.get('penyusunProduk')
        get_penyusunProduk = Material.objects.get(id = material_form.penyusunProduk)
        get_penggantiMaterial = Material.objects.get(id = eo_form.material)
        Material.objects.create(id=material_form.id, varian=get_varian, idMaterial=material_form.idMaterial,
                                namaMaterial=material_form.namaMaterial, namaSupplier=material_form.namaSupplier,
                                penyusunProduk=get_penyusunProduk, penggantiMaterial=get_penggantiMaterial,
                                is_berlaku = False)
        next = request.POST.get('next', '/')
        return redirect('engineeringOrder:index')

    context = {
        'JudulEO': 'Tambah Engineering Order',
        'JudulMat': 'Material Pengganti',
        'eo_form': eo_form,
        'material_form': material_form,
    }
    return render(request, 'engineeringOrder/newEO.html', context)

def deleteEO(request, delete_id):
    #cara delete
    EngineeringOrder.objects.filter(id=delete_id).delete()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)

def setuju(request,setuju_id):
    eo_update = EngineeringOrder.objects.get(id=setuju_id)
    matEO = str(eo_update.material.id)
    mat = Material.objects.get(id=matEO)
    mat_pengganti = Material.objects.get(penggantiMaterial=matEO)

    mat_kebutuhan = KebutuhanMaterial.objects.get(material=matEO)

    eo_form = PersetujuanEOForm(request.POST or None, instance=eo_update)

    if request.method == 'POST':
        tanggalPerubahanBerlaku = request.POST.get('tanggalPerubahanBerlaku')
        tanggal = datetime.datetime.now().date()
        EngineeringOrder.objects.filter(id=setuju_id).update(is_disetujui=True,
                                                                tanggalPersetujuan=tanggal,
                                                                tanggalPerubahanBerlaku=tanggalPerubahanBerlaku)

        if eo_update.material.id == mat.id:
            Material.objects.filter(id=mat.id).update(is_berlaku=False,
                                                          tanggalGanti=tanggalPerubahanBerlaku,
                                                          keterangan=eo_update.keterangan)
            Material.objects.filter(id=mat_pengganti.id).update(is_berlaku=True,
                                                      tanggalMulaiBerlaku=tanggalPerubahanBerlaku,)

        return HttpResponseRedirect("prosesEO/{id}".format(id=eo_update.id))

    context = {
        'Judul': 'Persetujuan Engineering Order',
        'Judul_Proses': 'Proses Material Sebelum',
        'eo_form': eo_form,
        'mat': mat,
        'eo_update': eo_update,
        'mat_kebutuhan': mat_kebutuhan,
    }
    return render(request, 'engineeringOrder/setuju.html', context)

def tidakSetuju(request,tidakSetuju_id):
    tanggal = datetime.datetime.now().date()
    eo_update = EngineeringOrder.objects.get(id=tidakSetuju_id)
    matEO = str(eo_update.material.id)
    mat = Material.objects.get(id=matEO)
    mat_pengganti = Material.objects.get(penggantiMaterial=matEO)

    EngineeringOrder.objects.filter(id=tidakSetuju_id).update(is_disetujui=False, tanggalPersetujuan=tanggal)
    Material.objects.filter(id=mat_pengganti.id).update(is_berlaku = None)
    return redirect('engineeringOrder:tidakDisetujui')

def belumDisetujui(request):
    eo = EngineeringOrder.objects.filter(is_disetujui__isnull=True)
    mat = Material.objects.all()
    context = {
        'Judul': 'Engineering Order Belum Disetujui',
        'eo': eo,
        'mat': mat,
    }
    return render(request, 'engineeringOrder/belumDisetujuiV2.html', context)

def disetujui(request):
    eo = EngineeringOrder.objects.filter(is_disetujui=True)
    mat = Material.objects.all()
    mat_pengganti = Material.objects.filter(is_berlaku = False)
    mat_kebutuhan = KebutuhanMaterial.objects.all()
    context = {
        'Judul': 'Engineering Order Disetujui',
        'eo': eo,
        'mat': mat,
        'mat_kebutuhan': mat_kebutuhan,
    }
    return render(request, 'engineeringOrder/disetujuiV2.html', context)

def tidakDisetujui(request):
    eo = EngineeringOrder.objects.filter(is_disetujui=False)
    mat = Material.objects.all()

    context = {
        'Judul': 'Engineering Order Tidak Disetujui',
        'eo': eo,
        'mat': mat,
    }
    return render(request, 'engineeringOrder/tidakDisetujuiV2.html', context)

def prosesEO(request, setuju_id):
    eo = EngineeringOrder.objects.get(id=setuju_id)
    matEO = str(eo.material.id)
    mat = Material.objects.get(id=matEO)
    mat_kebutuhan = KebutuhanMaterial.objects.get(material=matEO)

    context = {
        'Judul': 'Proses Material Sebelum',
        'mat': mat,
        'mat_kebutuhan': mat_kebutuhan,
        'eo': eo,
    }
    return render(request, 'engineeringOrder/prosesEO.html', context)


def prosesLamaEO(request, setuju_id):
    eo_update = EngineeringOrder.objects.get(id=setuju_id)
    material_ganti_eo = eo_update.material

    material_pengganti = Material.objects.get(penggantiMaterial = material_ganti_eo)
    mid = str(material_pengganti.idMaterial)
    idmaterial = Material.objects.filter(idMaterial=mid).first()

    material_ganti_kebutuhan = KebutuhanMaterial.objects.get(material=material_ganti_eo)

    EngineeringOrder.objects.filter(id=setuju_id).update(is_prosesBaru=False)
    KebutuhanMaterial.objects.filter(id=material_ganti_kebutuhan.id).delete()
    KebutuhanMaterial.objects.create(stasiunKerja=material_ganti_kebutuhan.stasiunKerja, proses=material_ganti_kebutuhan.proses,
                                     material=material_pengganti)

    proses_sk = Proses.objects.get(idProses=str(material_ganti_kebutuhan.proses))
    p_sk = str(proses_sk.stasiunKerja)
    stasiunKerja = StasiunKerja.objects.get(idStasiunKerja=p_sk)
    material = KebutuhanMaterial.objects.filter(stasiunKerja=stasiunKerja).filter(material__idMaterial=idmaterial).first()
    km = material.jumlahMaterialPerCycleTime
    kumulatif = km + 1
    KebutuhanMaterial.objects.filter(material__idMaterial=idmaterial).update(jumlahMaterialPerCycleTime=kumulatif)
    return redirect('engineeringOrder:disetujui')

def prosesBerlakuEO(request, setuju_id):
    eo = EngineeringOrder.objects.get(id=setuju_id)
    matEO = str(eo.material.id)
    mat = Material.objects.get(id=matEO)
    mat_kebutuhan = KebutuhanMaterial.objects.get(material=matEO)

    context = {
        'Judul': 'Proses Material Sebelum',
        'mat': mat,
        'mat_kebutuhan': mat_kebutuhan,
        'eo': eo,
    }
    return render(request, 'engineeringOrder/prosesBerlakuEO.html', context)

def prosesLamaBerlakuEO(request,setuju_id):
    eo = EngineeringOrder.objects.get(id=setuju_id)
    matEO = str(eo.material.id)
    mat_kebutuhan = KebutuhanMaterial.objects.get(material=matEO)
    mat_kebutuhan_proses = str(mat_kebutuhan.proses.idProses)
    proses = Proses.objects.get(idProses=mat_kebutuhan_proses)

    Proses.objects.filter(idProses=proses).update(is_berlaku=True)
    return HttpResponseRedirect("prosesEO/prosesBaruEO/{id}".format(id=eo.id))

def prosesLamaTidakBerlakuEO(request,setuju_id):
    eo = EngineeringOrder.objects.get(id=setuju_id)
    matEO = str(eo.material.id)
    mat_kebutuhan = KebutuhanMaterial.objects.get(material=matEO)
    mat_kebutuhan_proses = str(mat_kebutuhan.proses.idProses)
    proses = Proses.objects.get(idProses=mat_kebutuhan_proses)

    Proses.objects.filter(idProses=proses).update(is_berlaku=False, tanggalSelesaiBerlaku=eo.tanggalPerubahanBerlaku)
    return HttpResponseRedirect("prosesEO/prosesBaruEO/{id}".format(id=eo.id))

def prosesBaruEO(request, setuju_id):
    eo_update = EngineeringOrder.objects.get(id=setuju_id)
    proses_form = ProsesGantiForm(request.POST or None, instance=eo_update)

engineeringOrder/templates/engineeringOrder/belumDisetujui.html
{% extends "base.html" %}
{% load static %}


{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}

    <div class="container">
        <div class="card" style="margin-bottom:20px;margin-top:20px;">
            <div class="card-header" style="background-color:#d3d9df;">
                <div class="btn-group d-flex" role="group" >
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:index" %}">Semua Engineering Order</a>
                    <a type="button" class="btn btn-primary w-100" href="{% url "engineeringOrder:belumDisetujui" %}">Belum Disetujui</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:disetujui" %}">Disetujui</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:tidakDisetujui" %}">Tidak Disetujui</a>
                </div>
            </div>

            <div class="card-body">

                <table class="table table-hover text-center" style="background-color:white;">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nama Pengusul</th>
                        <th scope="col">Departemen Pengusul</th>
                        <th scope="col">Usulan Material yang Diubah</th>
                        <th scope="col">Keterangan</th>
                        <th scope="col">Tanggal Pengajuan</th>
                        <th scope="col">Persetujuan</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for eo in eo %}
                    <tr>
                        <td>{{eo.idEO}}</td>
                        <td>{{eo.namaPengusul}}</td>
                        <td>{{eo.departemenPengusul}}</td>
                        <td>
                            <b>ID Material: {{eo.material.idMaterial}}</b> <br>
                            Varian: {{eo.material.varian}} <br>
                            Supplier: {{eo.material.namaSupplier}} <br>
                            Penyusun Produk: {{eo.material.penyusunProduk}}
                        </td>
                        <td>{{eo.keterangan}}</td>
                        <td>{{eo.tanggalPengajuan|date:"d-m-Y"}}</td>
                        <td>
                            <a href="{% url "engineeringOrder:setujuEO" eo.id %}" class="btn btn-success"><i class="fa fa-check" aria-hidden="true"></i> Setuju</a>
                            <br> <br>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
                              <i class="fa fa-times" aria-hidden="true"></i> Tidak Setuju
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Engineering Order</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                    Apakah engineering order tidak disetujui?
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                    <a href="{% url "engineeringOrder:tidakSetujuEO" eo.id %}" class="btn btn-danger">Ya</a>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
{% endblock contents %}

engineeringOrder/templates/engineeringOrder/index.html
{% extends "base.html" %}
{% load static %}
{% load has_group %}


{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}

    <div class="container">
        <div class="card" style="margin-bottom:20px;margin-top:20px;">
            <div class="card-header" style="background-color:#d3d9df;">
                <div class="btn-group d-flex" role="group" >
                    <a type="button" class="btn btn-primary w-100" href="{% url "engineeringOrder:index" %}">Semua Engineering Order</a>
                    {% if request.user|has_group:"Designer" %}
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:belumDisetujui" %}">Belum Disetujui</a>
                    {% endif %}
                    {% if request.user|has_group:"Admin" %}
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:belumDisetujui" %}">Belum Disetujui</a>
                    {% endif %}
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:disetujui" %}">Disetujui</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "engineeringOrder:tidakDisetujui" %}">Tidak Disetujui</a>
                </div>
            </div>

            <div class="card-body">
                <div class="text-right" style="margin-bottom:20px;">
                    <div class="btn-group" role="group" aria-label="Basic outlined example">
                        <a class="btn btn-primary" href="{% url "engineeringOrder:newEO" %}">
                        <i class="fa fa-plus" aria-hidden="true"></i> Tambah Engineering Order
                        </a>
                    </div>
                </div>

                <table class="table table-hover text-center" style="background-color:white;">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Pengusul</th>
                        <th colspan="4">Usulan Material yang Diubah</th>
                        <th colspan="4">Material Pengganti</th>
                        <th scope="col">Alasan</th>
                        <th scope="col">Tanggal Pengajuan</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for eo in eo %}
                    <tr>
                        <td>{{eo.idEO}}</td>
                        <td>
                            Nama: {{eo.namaPengusul}}<br>
                            Departemen: {{eo.departemenPengusul}}
                        </td>
                        <td><b>ID Material: {{eo.material.idMaterial}}</b></td>
                        <td>Varian: {{eo.material.varian}}</td>
                        <td>Supplier: {{eo.material.namaSupplier}}</td>
                        <td>Penyusun Produk: {{eo.material.penyusunProduk}}</td>
                        {% for mat in mat %}
                        {% if eo.material == mat.penggantiMaterial %}
                        <td>
                            <b>ID Material: {{mat.idMaterial}}</b> <br>
                            Varian: {{mat.varian}} <br>
                            Supplier: {{mat.namaSupplier}} <br>
                            Penyusun Produk: {{mat.penyusunProduk}}
                        </td>
                        {% endif %}
                        {% endfor %}
                        <td>{{eo.keterangan}}</td>
                        <td>{{eo.tanggalPengajuan|date:"d-m-Y"}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
{% endblock contents %}

engineeringOrder/templates/engineeringOrder/newEO.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block Title %}
    Lini Produksi | {{JudulEO}}
{% endblock Title %}

{% block pageTitle %}

{% endblock pageTitle %}

{% block contents %}

    <div class="container" style="width: 50%;
    box-shadow: 0 3px 20px rgba(0,0,0,0.3);
    padding: 30px;
    margin-top: 90px;
    margin-bottom: 30px;
    margin-left: 25%">
        <form method="POST">
        {% csrf_token %}
            <fieldset class="from-group">
                <legend class="border-bottom mb-4" align="center">{{JudulEO}}</legend>
                {{eo_form|crispy}}
                <br>
                <legend class="border-bottom mb-4" align="center">{{JudulMat}}</legend>
                {{material_form|crispy}}
                <button type="Submit" class="btn btn-primary" style="width: 100%;">Submit</button>
            </fieldset>
        </form>
    </div>
{% endblock contents %}

engineeringOrder/templates/engineeringOrder/prosesBerlakuEO.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}

{% endblock pageTitle %}

{% block contents %}

    <div class="container" style="width: 50%;
    box-shadow: 0 3px 20px rgba(0,0,0,0.3);
    padding: 30px;
    margin-top: 150px;
    margin-bottom: 30px;
    margin-left: 25%">
            <fieldset class="from-group">
                <legend align="center">{{Judul}} ({{mat.idMaterial}})</legend>
            </fieldset>
            <table class="table">
                <tr>
                    <th>Stasiun Kerja</th>
                    <td>{{mat_kebutuhan.stasiunKerja}}</td>
                </tr>
                <tr>
                    <th>Proses</th>
                    <td>({{mat_kebutuhan.proses.idProses}}) {{mat_kebutuhan.proses.namaProses}}</td>
                </tr>
            </table>
            <br>
        <div class="text-center">
            <h3>Apakah proses sebelum tetap berlaku?</h3>
            <a href="{% url "engineeringOrder:prosesLamaBerlakuEO" eo.id %}" class="btn btn-success"><i class="fa fa-check" aria-hidden="true"></i> Ya</a>
            <br>
            <br>
            <a href="{% url "engineeringOrder:prosesLamaTidakBerlakuEO" eo.id %}" class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i> Tidak</a>
        </div>
    </div>
{% endblock contents %}

engineeringOrder/templates/engineeringOrder/prosesEO.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}

{% endblock pageTitle %}

{% block contents %}

    <div class="container" style="width: 50%;
    box-shadow: 0 3px 20px rgba(0,0,0,0.3);
    padding: 30px;
    margin-top: 160px;
    margin-bottom: 30px;
    margin-left: 25%">
            <fieldset class="from-group">
                <legend align="center">{{Judul}} ({{mat.idMaterial}})</legend>
            </fieldset>
            <table class="table">
                <tr>
                    <th>Stasiun Kerja</th>
                    <td>{{mat_kebutuhan.stasiunKerja}}</td>
                </tr>
                <tr>
                    <th>Proses</th>
                    <td>({{mat_kebutuhan.proses.idProses}}) {{mat_kebutuhan.proses.namaProses}}</td>
                </tr>
            </table>
            <br>
        <div class="text-center">
            <h5>Apakah material baru ditangani proses lama atau baru?</h5>
            <a href="{% url "engineeringOrder:prosesLamaEO" eo.id %}" class="btn btn-warning">Proses Lama</a>
            <br>
            <br>
            <a href="{% url "engineeringOrder:prosesBerlakuEO" eo.id %}" class="btn btn-success">Proses Baru</a>
        </div>
    </div>
{% endblock contents %}