SistemPenjadwalan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import viewsBatchProduction

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls','users')),
    path('liniProduksi/', include('liniProduksi.urls','liniProduksi')),
    path('produk/', include('produk.urls','produk')),
    path('jadwal/', include('jadwal.urls','jadwal')),
    path('engineeringOrder/', include('engineeringOrder.urls','engineeringOrder')),
    path('contributor/',views.contributor, name='contributor'),
    path('home/',views.home, name='home'),
    path('', views.index, name='index'),
    path('batch/about/', viewsBatchProduction.about, name='about'),
    path('batch/about/&', viewsBatchProduction.dz, name='dz'),
    path('login/', viewsBatchProduction.loginview, name='login'),
    path('logout/', viewsBatchProduction.logoutview, name='logout'),
    path('plant/', viewsBatchProduction.plant, name='plant'),
    path('batch/', include('BatchProduction.urls'), name='batch'),
    path('<slug:instance>/', viewsBatchProduction.notfound, name='404'),
    # path('', viewsBatchProduction.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liniProduksi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views, viewsStasiunKerja, viewsStasiunKerjaDetail, viewsMaterial, viewsProses, viewsPeralatanProduksi, viewsOperator, viewsLiniProduksi_harian, viewsPengirimanMaterial, viewsGangguan
app_name = 'liniProduksi'

urlpatterns = [
    path('gangguanStasiunKerja/gangguanSelesai/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanSelesai, name='gangguanSelesai'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanForm, name='gangguanForm'),
    path('gangguanStasiunKerja/liniProduksiTerhenti/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.liniProduksiTerhenti, name='liniProduksiTerhenti'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>', viewsGangguan.indikasiMasalah, name='indikasiMasalah'),
    path('gangguanStasiunKerja/<str:idStasiunKerjaInput>', viewsGangguan.gangguanStasiunKerja, name='gangguanSK'),
    path('gangguanStasiunKerja/semua/', viewsGangguan.gangguan_semua, name='gangguanSemua'),
    path('gangguanStasiunKerja/', viewsGangguan.gangguan, name='gangguan'),
    path('updateMaterial/<str:update_id>', viewsMaterial.updateMaterial, name='updateMaterial'),
    path('deleteMaterial/<str:delete_id>', viewsMaterial.deleteMaterial, name='deleteMaterial'),
    path('updateStasiunKerja/<str:update_id>', viewsStasiunKerja.updateStasiunKerja, name='updateStasiunKerja'),
    path('deleteStasiunKerja/<str:delete_id>', viewsStasiunKerja.deleteStasiunKerja, name='deleteStasiunKerja'),
    path('updateLiniProduksi/<str:update_id>', views.updateLiniProduksi, name='updateLiniProduksi'),
    path('deleteLiniProduksi/<str:delete_id>', views.deleteLiniProduksi, name='deleteLiniProduksi'),
    path('updateProses/<str:update_id>', viewsProses.updateProses, name='updateProses'),
    path('deleteProses/<str:delete_id>', viewsProses.deleteProses, name='deleteProses'),
    path('updatePeralatanProduksi/<str:update_id>', viewsPeralatanProduksi.updatePeralatanProduksi, name='updatePeralatanProduksi'),
    path('deletePeralatanProduksi/<str:delete_id>', viewsPeralatanProduksi.deletePeralatanProduksi, name='deletePeralatanProduksi'),
    path('updateOperator/<str:update_id>', viewsOperator.updateOperator, name='updateOperator'),
    path('deleteOperator/<str:delete_id>', viewsOperator.deleteOperator, name='deleteOperator'),
    path('newProses/', viewsProses.newProses, name='newProses'),
    path('newPeralatanProduksi/', viewsPeralatanProduksi.newPeralatanProduksi, name='newPeralatanProduksi'),
    path('newKebutuhanMaterial/', viewsMaterial.newMaterial, name='newKebutuhanMaterial'),
    path('newLiniProduksi/', views.newLiniProduksi, name='newLiniProduksi'),
    path('newStasiunKerja/',viewsStasiunKerja.newStasiunKerja, name='newStasiunKerja'),
    path('newOperator/',viewsOperator.newOperator, name='newOperator'),
    path('newPengirimanMaterial/',viewsPengirimanMaterial.newPengirimanMaterial, name='newPengirimanMaterial'),
    path('updatePengirimanMaterial/<str:update_id>', viewsPengirimanMaterial.updatePengirimanMaterial,
         name='updatePengirimanMaterial'),
    path('deletePengirimanMaterial/<str:delete_id>', viewsPengirimanMaterial.deletePengirimanMaterial,
         name='deletePengirimanMaterial'),
    path('updateTargetHarian/<str:update_id>', viewsLiniProduksi_harian.updateTargetHarian, name='updateTargetHarian'),
    path('deleteTargetHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetHarian, name='deleteTargetHarian'),
    path('produksiHarian/newTargetHarian/<str:produksiHarianInput>',viewsLiniProduksi_harian.newTargetHarian, name='newTargetHarian'),
    path('produksiHarian/newWaktuIstirahat/<str:produksiHarianInput>',viewsLiniProduksi_harian.newWaktuIstirahat, name='newWaktuIstirahat'),
    path('updateWaktuIstirahat/<str:update_id>', viewsLiniProduksi_harian.updateWaktuIstirahat, name='updateWaktuIstirahat'),
    path('deleteWaktuIstirahat/<str:delete_id>', viewsLiniProduksi_harian.deleteWaktuIstirahat, name='deleteWaktuIstirahat'),
    path('updateTargetTahunan/<str:update_id>', viewsLiniProduksi_harian.updateTargetTahunan, name='updateTargetTahunan'),
    path('deleteTargetTahunan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetTahunan, name='deleteTargetTahunan'),
    path('newTargetTahunan/',viewsLiniProduksi_harian.newTargetTahunan, name='newTargetTahunan'),
    path('updateTargetBulanan/<str:update_id>', viewsLiniProduksi_harian.updateTargetBulanan, name='updateTargetBulanan'),
    path('deleteTargetBulanan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetBulanan, name='deleteTargetBulanan'),
    path('newTargetBulanan/',viewsLiniProduksi_harian.newTargetBulanan, name='newTargetBulanan'),
    path('updateTargetMingguan/<str:update_id>', viewsLiniProduksi_harian.updateTargetMingguan, name='updateTargetMingguan'),
    path('deleteTargetMingguan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetMingguan, name='deleteTargetMingguan'),
    path('newTargetMingguan/',viewsLiniProduksi_harian.newTargetMingguan, name='newTargetMingguan'),
    path('newHariLibur/',viewsLiniProduksi_harian.hariLibur, name='newHariLibur'),
    path('newIstirahatNormal/',viewsLiniProduksi_harian.newWaktuIstirahatNormal, name='newIstirahatNormal'),
    path('newProduksiHarian/',viewsLiniProduksi_harian.newProduksiHarian, name='newProduksiHarian'),
    path('updateProduksiHarian/<str:update_id>', viewsLiniProduksi_harian.updateProduksiHarian, name='updateProduksiHarian'),
    path('deleteProduksiHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteProduksiHarian, name='deleteProduksiHarian'),
    path('<str:idLiniProduksiInput>/<str:idStasiunKerjaInput>/', viewsStasiunKerjaDetail.stasiunKerjaDetail, name='stasiunKerjaDetail'),
    path('produksiTahunan/', viewsLiniProduksi_harian.tahunan, name='tahunan'),
    path('produksiBulanan/', viewsLiniProduksi_harian.bulanan, name='bulanan'),
    path('produksiMingguan/', viewsLiniProduksi_harian.mingguan, name='mingguan'),
    path('produksiHarian/', viewsLiniProduksi_harian.harian, name='harian'),
    path('produksi/', viewsLiniProduksi_harian.produksiHarian, name='produksiHarian'),
    path('tambahCapaianProduksi/<str:id>', viewsLiniProduksi_harian.tambahCapaian, name='tambahCapaian'),
    path('<str:idLiniProduksiInput>/', viewsStasiunKerja.stasiunKerja, name='stasiunKerja'),
    path('', views.index, name='index'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views
app_name = 'users'

urlpatterns = [
    path('', views.registerView, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

liniProduksi/views.py
from django.shortcuts import render, redirect

from .models import LiniProduksi
from .forms import LiniProduksiForm
# Create your views here.

# def liniProduksi(request, idBrandInput, idModelInput, idVarianInput):
#     # if request.method=="POST":
#     #     fromdate = request.POST.get('fromdate')
#     #     todate = request.POST.get('todate')
#     #     namaLP = request.POST.get('namaLP')
#     #     searchresult = LiniProduksi.objects.raw('select id,idLiniProduksi,waktuMulaiProduksi,waktuSelesaiProduksi,waktuSiklus,tanggalMulaiProduksi FROM produk_liniproduksi WHERE ((idLiniProduksi = "'+namaLP+'") OR (tanggalMulaiProduksi between "'+fromdate+'" and "'+todate+'")) ')
#     #     context = {
#     #         'Judul': 'Lini Produksi',
#     #         'semua_liniProduksi': searchresult,
#     #
#     #         'css': 'produk/css/styles_table.css',
#     #     }
#     #     return render(request,'produk/index.html', context)
#     # else:
#     model_p = LiniProduksi.objects.filter(brand__id=idBrandInput)
#     varian_p = Varian.objects.filter(id=idVarianInput)
#     liniProduksi = LiniProduksi.objects.filter(varian__id=idVarianInput)
#     context = {
#         'Judul': 'Lini Produksi',
#         'liniProduksi': liniProduksi,
#         'model_p':model_p,
#         'varian_p': varian_p,
#         'css': 'produk/css/styles_table.css',
#     }
#     return render(request,'produk/liniProduksi.html',context)

def index(request):
    liniProduksi = LiniProduksi.objects.all()

    context = {
        'Judul': 'Lini Produksi',
        'liniProduksi': liniProduksi,
        'css': 'produk/css/styles_table.css',
    }
    return render(request, 'liniProduksi/indexV2.html', context)


def newLiniProduksi(request):
    #cara mencocokan antara input dengan data yang telah ada = PostForm(request.POST)
    liniProduksi_form = LiniProduksiForm(request.POST or None)

    # masukin data dari form ke database
    if request.method == 'POST':
        # validasi data
        if liniProduksi_form.is_valid():
            # menyimpan ke database
            liniProduksi_form.save()
            return redirect('liniProduksi:index')
    context = {
        'Judul': 'Tambah Lini Produksi',
        'css': 'produk/css/styles_form.css',
        'liniProduksi_form': liniProduksi_form,
    }
    return render(request,'liniProduksi/newLiniProduksi.html',context)

def deleteLiniProduksi(request, delete_id):
    #cara delete
    LiniProduksi.objects.filter(id=delete_id).delete()
    return redirect('liniProduksi:index')

def updateLiniProduksi(request, update_id):
    #cara edit
    liniProduksi_update = LiniProduksi.objects.get(id=update_id)

    data = {
        'idLiniProduksi': liniProduksi_update.idLiniProduksi,
        'waktuSiklus': liniProduksi_update.waktuSiklus,
        'jumlahStasiunKerja': liniProduksi_update.jumlahStasiunKerja,
    }
    liniProduksi_form = LiniProduksiForm(request.POST or None, initial=data, instance=liniProduksi_update)

    if request.method == 'POST':
        #validasi data
        if liniProduksi_form.is_valid():
            #menyimpan ke database
            liniProduksi_form.save()
            return redirect('liniProduksi:index')

    context = {
        'Judul': 'Update Lini Produksi',
        'liniProduksi_form': liniProduksi_form,
    }

    return render(request,'liniProduksi/newLiniProduksi.html',context)

liniProduksi/templates/liniProduksi/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <style>
        #tb2 tr, th, td {
            border:hidden;
        }

        table {
            background-color:white;
            margin:auto;
            width:60%;
            text-align: left;
            margin-top: 20px;
        }

        .card {
            margin-top: 20px;
        }

    </style>
{% endblock css %}

{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    <link rel="stylesheet" type='text/css' href="{% static css %}">

    <div class="container">
        <div class="card" style="margin-top:15px; margin-bottom: 20px;">
            <div class="card-header" style="background-color:#d3d9df;">
                <div class="btn-group d-flex" role="group" >
                    <a type="button" class="btn btn-primary w-100" href="{% url "liniProduksi:index" %}">Lini Produksi</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "liniProduksi:targetProduksi" %}">Target Produksi</a>
                </div>
            </div>

            <div class="card-body">
                <div class="text-right" style="margin-bottom:20px;">
          <div class="btn-group">
              <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-plus" aria-hidden="true"></i> Tambah
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{% url "liniProduksi:newLiniProduksi" %}">Lini Produksi</a>
                  <a class="dropdown-item" href="{% url "liniProduksi:newTargetProduksi" %}">Target Produksi</a>
              </div>
          </div>
          </div>
      </div>
                <table id="myTable" class="table table-hover text-center" style="background-color:white; margin-top:20px;">
                    <thead>
                    <tr>
                        <th>ID Lini Produksi</th>
                        <th>Waktu Produksi</th>
                        <th>Waktu Siklus (s)</th>
                        <th>Jumlah Stasiun Kerja</th>
                        <th>List Stasiun Kerja</th>
                        <th>Opsi</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for lp in liniProduksi %}
                        <tr>
                            <td>{{lp.idLiniProduksi}}</td>
                            <td>{{lp.waktuMulaiProduksi|time:"H:i:s"}} s/d {{lp.waktuSelesaiProduksi|time:"H:i:s"}}</td>
                            <td>{{lp.waktuSiklus}}</td>
                            <td>{{lp.jumlahStasiunKerja}}</td>
                            <td><a href="{% url "liniProduksi:stasiunKerja" idLiniProduksiInput=lp.idLiniProduksi %}">list</a></td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{% url "liniProduksi:deleteLiniProduksi" lp.id %}">Hapus</a>
                                        <a class="dropdown-item" href="{% url "liniProduksi:updateLiniProduksi" lp.id %}">Edit</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock contents %}

liniProduksi/templates/liniProduksi/produksi_tahunan.html
{% extends "base.html" %}
{% load static %}
{% load templatetags %}

{% block css %}
    <style>
        #tb2 tr, th, td {
            border:hidden;
        }

        table {
            background-color:white;
            margin:auto;
            width:60%;
            text-align: left;
            margin-top: 20px;
        }

        .card {
            margin-top: 20px;
        }

        .card2 {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            background-color:#f5f5f5;
        }

        .card2:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            background-color: #d3d9df;
        }

    </style>
{% endblock css %}

{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    <link rel="stylesheet" type='text/css' href="{% static css %}">

    <div class="container" style="margin-bottom:20px;margin-top:13px;">
    <div class="text-right" style="margin-bottom:20px;">
        {% if request.user|has_group:"Staf produksi" %}
        <div class="text-right" style="margin-bottom:20px;">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetTahunan" %}">Target Tahunan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetBulanan" %}">Target Bulanan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetMingguan" %}">Target Mingguan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newProduksiHarian" %}">Produksi Harian</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newHariLibur" %}">Hari Libur</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newIstirahatNormal" %}">Waktu Istirahat Normal</a>
            </div>
        </div>
    </div>
        {% endif %}

        {% if request.user|has_group:"Admin" %}
        <div class="text-right" style="margin-bottom:20px;">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetTahunan" %}">Target Tahunan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetBulanan" %}">Target Bulanan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newTargetMingguan" %}">Target Mingguan</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newProduksiHarian" %}">Produksi Harian</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newHariLibur" %}">Hari Libur</a>
                <a class="dropdown-item" href="{% url "liniProduksi:newIstirahatNormal" %}">Waktu Istirahat Normal</a>
            </div>
        </div>
    </div>
        {% endif %}
    </div>
    </div>

    <div class="container">
        <div class="card" style="margin-top:15px; margin-bottom: 20px;">
            <div class="card-header" style="background-color:#d3d9df;">
                <div class="btn-group d-flex" role="group" >
                    <a type="button" class="btn btn-link w-100" href="{% url "liniProduksi:produksiHarian" %}">Sekarang</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "liniProduksi:harian" %}">Harian</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "liniProduksi:mingguan" %}">Mingguan</a>
                    <a type="button" class="btn btn-link w-100" href="{% url "liniProduksi:bulanan" %}">Bulanan</a>
                    <a type="button" class="btn btn-primary w-100" href="{% url "liniProduksi:tahunan" %}">Tahunan</a>
                </div>
            </div>

            <div class="card-body">
                <table class="table text-center table-hover">
                    <thead>
                    <th>ID Lini Produksi</th>
                    <th>ID Varian</th>
                    <th>Tahun</th>
                    <th>Target</th>
                    <th>Capaian</th>
                    <th>Persentase Capaian</th>
                    {% if request.user|has_group:"Staf produksi" %}
                    <th>Opsi</th>
                    {% endif %}
                    {% if request.user|has_group:"Admin" %}
                    <th>Opsi</th>
                    {% endif %}
                    </thead>
                    {% for lp in targetTahunan %}
                    <tbody>
                    <td>
                        {{lp.liniProduksi}}
                    </td>
                    <td>{{lp.varian}}</td>
                    <td>{{lp.tahun}}</td>
                    {% for th in targetHarian %}
                        {% if lp.tahun == th.year %}
                        {% if lp.varian_id == th.varian %}
                    <td>
                        {{lp.target}}
                    </td>
                    <td>{{th.sum_capaian}}</td>
                    <td>{% widthratio th.sum_capaian lp.target 100 %} %</td>
                    {% if request.user|has_group:"Staf produksi" %}
                    <td>
                        {% if lp.tahun >= yr %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url "liniProduksi:deleteTargetTahunan" lp.id %}">Hapus</a>
                                <a class="dropdown-item" href="{% url "liniProduksi:updateTargetTahunan" lp.id %}">Edit</a>
                            </div>
                        </div>
                        {% endif %}
                    </td>
                    {% endif %}

                    {% if request.user|has_group:"Admin" %}
                    <td>
                        {% if lp.tahun >= yr %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url "liniProduksi:deleteTargetTahunan" lp.id %}">Hapus</a>
                                <a class="dropdown-item" href="{% url "liniProduksi:updateTargetTahunan" lp.id %}">Edit</a>
                            </div>
                        </div>
                        {% endif %}
                    </td>
                    {% endif %}

                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    </tbody>
                    {% endfor %}
                </table>

            </div>
        </div>
    </div>

{% endblock contents %}

liniProduksi/templates/liniProduksi/stasiunKerjaDetail.html
{% extends "base.html" %}
{% load static %}
{% load templatetags %}

{% block css %}
    <style>
        #tb2 tr, th, td {
            border:hidden;
        }

        table {
            background-color:white;
            margin:auto;
            width:60%;
            text-align: left;
            margin-top: 20px;
        }

        .card {
            margin-top: 20px;
        }
    </style>
{% endblock css %}

{% block Title %}
    Lini Produksi | {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    <link rel="stylesheet" type='text/css' href="{% static css %}">
    <div class="container" style="margin-bottom:20px;margin-top:13px;">
        {% include "liniProduksi/snippets/stasiunKerjaDetail_breadcumb.html" %}
        {% include "liniProduksi/snippets/stasiunKerjaDetail_informasiUmum.html" %}
        <div class="text-right" style="margin-top:20px;">
            {% if request.user|has_group:"Designer" %}
        <div class="dropup">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url "liniProduksi:newProses" %}?next={{ request.path|urlencode }}">Proses</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newOperator" %}?next={{ request.path|urlencode }}">Operator</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newPeralatanProduksi" %}?next={{ request.path|urlencode }}">Peralatan Produksi</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newKebutuhanMaterial" %}?next={{ request.path|urlencode }}">Kebutuhan Material</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newPengirimanMaterial" %}?next={{ request.path|urlencode }}">Informasi Pengiriman Material</a>
                    </div>
        </div>
            {% endif %}

            {% if request.user|has_group:"Operator" %}
        <div class="dropup">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% for sk in stasiunKerja %}
                        <a class="dropdown-item" href="{% url "liniProduksi:gangguanSK" sk.idStasiunKerja %}">Gangguan</a>
                        {% endfor %}
                    </div>
        </div>
            {% endif %}

            {% if request.user|has_group:"Admin" %}
        <div class="dropup">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url "liniProduksi:newProses" %}?next={{ request.path|urlencode }}">Proses</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newOperator" %}?next={{ request.path|urlencode }}">Operator</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newPeralatanProduksi" %}?next={{ request.path|urlencode }}">Peralatan Produksi</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newKebutuhanMaterial" %}?next={{ request.path|urlencode }}">Kebutuhan Material</a>
                        <a class="dropdown-item" href="{% url "liniProduksi:newPengirimanMaterial" %}?next={{ request.path|urlencode }}">Informasi Pengiriman Material</a>
                        {% for sk in stasiunKerja %}
                        <a class="dropdown-item" href="{% url "liniProduksi:gangguanSK" sk.idStasiunKerja %}">Gangguan</a>
                        {% endfor %}
                    </div>
        </div>
            {% endif %}

        </div>
        <div class="card">
            {% include "liniProduksi/snippets/stasiunKerjaDetail_card_nav.html" %}
            <div class="card-body tab-content">
                {% include "liniProduksi/stasiunKerjaDetail_proses.html" %}
                {% include "liniProduksi/stasiunKerjaDetail_operator.html" %}
                {% include "liniProduksi/stasiunKerjaDetail_peralatanProduksi.html" %}
                {% include "liniProduksi/stasiunKerjaDetail_material.html" %}
                {% include "liniProduksi/stasiunKerjaDetail_pengirimanMaterial.html" %}
            </div>
        </div>

    </div>

{% endblock contents %}