SistemPenjadwalan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import viewsBatchProduction

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls','users')),
    path('liniProduksi/', include('liniProduksi.urls','liniProduksi')),
    path('produk/', include('produk.urls','produk')),
    path('jadwal/', include('jadwal.urls','jadwal')),
    path('engineeringOrder/', include('engineeringOrder.urls','engineeringOrder')),
    path('contributor/',views.contributor, name='contributor'),
    path('home/',views.home, name='home'),
    path('', views.index, name='index'),
    path('batch/about/', viewsBatchProduction.about, name='about'),
    path('batch/about/&', viewsBatchProduction.dz, name='dz'),
    path('login/', viewsBatchProduction.loginview, name='login'),
    path('logout/', viewsBatchProduction.logoutview, name='logout'),
    path('plant/', viewsBatchProduction.plant, name='plant'),
    path('batch/', include('BatchProduction.urls'), name='batch'),
    path('<slug:instance>/', viewsBatchProduction.notfound, name='404'),
    # path('', viewsBatchProduction.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engineeringOrder/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'engineeringOrder'

urlpatterns = [
    path('tidakDisetujui/', views.tidakDisetujui, name='tidakDisetujui'),
    path('disetujui/', views.disetujui, name='disetujui'),
    path('belumDisetujui/', views.belumDisetujui, name='belumDisetujui'),
    path('tidakSetujuEngineeringOrder/<str:tidakSetuju_id>', views.tidakSetuju, name='tidakSetujuEO'),
    path('setujuEngineeringOrder/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaBerlakuEO/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaTidakBerlakuEO/prosesEO/prosesBaruEO/<str:setuju_id>', views.prosesBaruEO, name='prosesBaruEO'),
    path('setujuEngineeringOrder/prosesLamaBerlakuEO/<str:setuju_id>', views.prosesLamaBerlakuEO, name='prosesLamaBerlakuEO'),
    path('setujuEngineeringOrder/prosesLamaTidakBerlakuEO/<str:setuju_id>', views.prosesLamaTidakBerlakuEO, name='prosesLamaTidakBerlakuEO'),
    path('setujuEngineeringOrder/prosesBerlakuEO/<str:setuju_id>', views.prosesBerlakuEO, name='prosesBerlakuEO'),
    path('setujuEngineeringOrder/prosesLamaEO/<str:setuju_id>', views.prosesLamaEO, name='prosesLamaEO'),
    path('setujuEngineeringOrder/prosesEO/<str:setuju_id>', views.prosesEO, name='prosesEO'),
    path('setujuEngineeringOrder/<str:setuju_id>', views.setuju, name='setujuEO'),
    path('deleteEngineeringOrder/<str:delete_id>', views.deleteEO, name='deleteEO'),
    path('newEngineeringOrder/', views.newEO, name='newEO'),
    path('', views.index, name='index'),
]

jadwal/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'jadwal'

urlpatterns = [
    path('belumKonfirmasi/<str:idStasiunKerjaInput>/', views.belumKonfirmasi_SK, name='belumKonfirmasi_SK'),
    path('belumKonfirmasi/', views.belumKonfirmasi, name='belumKonfirmasi'),
    path('sudahKonfirmasi/<str:idStasiunKerjaInput>/', views.sudahKonfirmasi_SK, name='sudahKonfirmasi_SK'),
    path('sudahKonfirmasi/', views.sudahKonfirmasi, name='sudahKonfirmasi'),
    path('konfirmasi/<str:konfirmasi_id>', views.newKonfirmasi, name='konfirmasi'),
    path('jadwalTersedia/', views.jadwalTersedia, name='jadwalTersedia'),
    path('permintaanMaterial/<str:pm_id>', views.permintaanMaterial, name='permintaanMaterial'),
    path('<str:idStasiunKerjaInput>/', views.index_SK, name='index_SK'),
    path('', views.index, name='index'),
]

liniProduksi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views, viewsStasiunKerja, viewsStasiunKerjaDetail, viewsMaterial, viewsProses, viewsPeralatanProduksi, viewsOperator, viewsLiniProduksi_harian, viewsPengirimanMaterial, viewsGangguan
app_name = 'liniProduksi'

urlpatterns = [
    path('gangguanStasiunKerja/gangguanSelesai/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanSelesai, name='gangguanSelesai'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanForm, name='gangguanForm'),
    path('gangguanStasiunKerja/liniProduksiTerhenti/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.liniProduksiTerhenti, name='liniProduksiTerhenti'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>', viewsGangguan.indikasiMasalah, name='indikasiMasalah'),
    path('gangguanStasiunKerja/<str:idStasiunKerjaInput>', viewsGangguan.gangguanStasiunKerja, name='gangguanSK'),
    path('gangguanStasiunKerja/semua/', viewsGangguan.gangguan_semua, name='gangguanSemua'),
    path('gangguanStasiunKerja/', viewsGangguan.gangguan, name='gangguan'),
    path('updateMaterial/<str:update_id>', viewsMaterial.updateMaterial, name='updateMaterial'),
    path('deleteMaterial/<str:delete_id>', viewsMaterial.deleteMaterial, name='deleteMaterial'),
    path('updateStasiunKerja/<str:update_id>', viewsStasiunKerja.updateStasiunKerja, name='updateStasiunKerja'),
    path('deleteStasiunKerja/<str:delete_id>', viewsStasiunKerja.deleteStasiunKerja, name='deleteStasiunKerja'),
    path('updateLiniProduksi/<str:update_id>', views.updateLiniProduksi, name='updateLiniProduksi'),
    path('deleteLiniProduksi/<str:delete_id>', views.deleteLiniProduksi, name='deleteLiniProduksi'),
    path('updateProses/<str:update_id>', viewsProses.updateProses, name='updateProses'),
    path('deleteProses/<str:delete_id>', viewsProses.deleteProses, name='deleteProses'),
    path('updatePeralatanProduksi/<str:update_id>', viewsPeralatanProduksi.updatePeralatanProduksi, name='updatePeralatanProduksi'),
    path('deletePeralatanProduksi/<str:delete_id>', viewsPeralatanProduksi.deletePeralatanProduksi, name='deletePeralatanProduksi'),
    path('updateOperator/<str:update_id>', viewsOperator.updateOperator, name='updateOperator'),
    path('deleteOperator/<str:delete_id>', viewsOperator.deleteOperator, name='deleteOperator'),
    path('newProses/', viewsProses.newProses, name='newProses'),
    path('newPeralatanProduksi/', viewsPeralatanProduksi.newPeralatanProduksi, name='newPeralatanProduksi'),
    path('newKebutuhanMaterial/', viewsMaterial.newMaterial, name='newKebutuhanMaterial'),
    path('newLiniProduksi/', views.newLiniProduksi, name='newLiniProduksi'),
    path('newStasiunKerja/',viewsStasiunKerja.newStasiunKerja, name='newStasiunKerja'),
    path('newOperator/',viewsOperator.newOperator, name='newOperator'),
    path('newPengirimanMaterial/',viewsPengirimanMaterial.newPengirimanMaterial, name='newPengirimanMaterial'),
    path('updatePengirimanMaterial/<str:update_id>', viewsPengirimanMaterial.updatePengirimanMaterial,
         name='updatePengirimanMaterial'),
    path('deletePengirimanMaterial/<str:delete_id>', viewsPengirimanMaterial.deletePengirimanMaterial,
         name='deletePengirimanMaterial'),
    path('updateTargetHarian/<str:update_id>', viewsLiniProduksi_harian.updateTargetHarian, name='updateTargetHarian'),
    path('deleteTargetHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetHarian, name='deleteTargetHarian'),
    path('produksiHarian/newTargetHarian/<str:produksiHarianInput>',viewsLiniProduksi_harian.newTargetHarian, name='newTargetHarian'),
    path('produksiHarian/newWaktuIstirahat/<str:produksiHarianInput>',viewsLiniProduksi_harian.newWaktuIstirahat, name='newWaktuIstirahat'),
    path('updateWaktuIstirahat/<str:update_id>', viewsLiniProduksi_harian.updateWaktuIstirahat, name='updateWaktuIstirahat'),
    path('deleteWaktuIstirahat/<str:delete_id>', viewsLiniProduksi_harian.deleteWaktuIstirahat, name='deleteWaktuIstirahat'),
    path('updateTargetTahunan/<str:update_id>', viewsLiniProduksi_harian.updateTargetTahunan, name='updateTargetTahunan'),
    path('deleteTargetTahunan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetTahunan, name='deleteTargetTahunan'),
    path('newTargetTahunan/',viewsLiniProduksi_harian.newTargetTahunan, name='newTargetTahunan'),
    path('updateTargetBulanan/<str:update_id>', viewsLiniProduksi_harian.updateTargetBulanan, name='updateTargetBulanan'),
    path('deleteTargetBulanan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetBulanan, name='deleteTargetBulanan'),
    path('newTargetBulanan/',viewsLiniProduksi_harian.newTargetBulanan, name='newTargetBulanan'),
    path('updateTargetMingguan/<str:update_id>', viewsLiniProduksi_harian.updateTargetMingguan, name='updateTargetMingguan'),
    path('deleteTargetMingguan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetMingguan, name='deleteTargetMingguan'),
    path('newTargetMingguan/',viewsLiniProduksi_harian.newTargetMingguan, name='newTargetMingguan'),
    path('newHariLibur/',viewsLiniProduksi_harian.hariLibur, name='newHariLibur'),
    path('newIstirahatNormal/',viewsLiniProduksi_harian.newWaktuIstirahatNormal, name='newIstirahatNormal'),
    path('newProduksiHarian/',viewsLiniProduksi_harian.newProduksiHarian, name='newProduksiHarian'),
    path('updateProduksiHarian/<str:update_id>', viewsLiniProduksi_harian.updateProduksiHarian, name='updateProduksiHarian'),
    path('deleteProduksiHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteProduksiHarian, name='deleteProduksiHarian'),
    path('<str:idLiniProduksiInput>/<str:idStasiunKerjaInput>/', viewsStasiunKerjaDetail.stasiunKerjaDetail, name='stasiunKerjaDetail'),
    path('produksiTahunan/', viewsLiniProduksi_harian.tahunan, name='tahunan'),
    path('produksiBulanan/', viewsLiniProduksi_harian.bulanan, name='bulanan'),
    path('produksiMingguan/', viewsLiniProduksi_harian.mingguan, name='mingguan'),
    path('produksiHarian/', viewsLiniProduksi_harian.harian, name='harian'),
    path('produksi/', viewsLiniProduksi_harian.produksiHarian, name='produksiHarian'),
    path('tambahCapaianProduksi/<str:id>', viewsLiniProduksi_harian.tambahCapaian, name='tambahCapaian'),
    path('<str:idLiniProduksiInput>/', viewsStasiunKerja.stasiunKerja, name='stasiunKerja'),
    path('', views.index, name='index'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

produk/urls.py
from django.contrib import admin
from django.urls import path

from . import views, viewsMaterial
app_name = 'produk'

urlpatterns = [
    path('riwayatMaterial/<str:idRiwayatMaterial>', viewsMaterial.riwayat, name='riwayatMaterial'),
    path('updateMaterial/<str:update_id>', viewsMaterial.updateMaterial, name='updateMaterial'),
    path('deleteMaterial/<str:delete_id>', viewsMaterial.deleteMaterial, name='deleteMaterial'),
    path('newMaterial/', viewsMaterial.newMaterial, name='newMaterial'),
    path('updateVarian/<str:update_id>', views.updateVarian, name='updateVarian'),
    path('deleteVarian/<str:delete_id>', views.deleteVarian, name='deleteVarian'),
    path('newVarian/', views.newVarian, name='newVarian'),
    path('<str:idVarianInput>/', viewsMaterial.billOfMaterial, name='billOfMaterial'),
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from . import views
app_name = 'users'

urlpatterns = [
    path('', views.registerView, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

templates/snippets/mainNavbar.html
{% load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand ml-5" href="{% url "index" %}">
    ADiMS
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto mr-5">
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url "users:logout" %}">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

templates/snippets/navbar.html
{% load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand ml-5" href="{% url "home" %}">
     Lini Produksi
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "home" %}">Home <span class="sr-only"></span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url "produk:index" %}">Produk</a>
          <a class="dropdown-item" href="{% url "liniProduksi:index" %}">Lini Produksi</a>
          <a class="dropdown-item" href="{% url "liniProduksi:produksiHarian" %}">Produksi</a>
          <a class="dropdown-item" href="{% url "jadwal:index" %}">Jadwal</a>
          <a class="dropdown-item" href="{% url "liniProduksi:gangguan" %}">Gangguan</a>
          <a class="dropdown-item" href="{% url "engineeringOrder:index" %}">Engineering Order</a>
        </div>
      </li>

       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url "users:logout" %}">Logout</a>
        </div>
      </li>

    </ul>
  </div>
</nav>

templates/snippets/navbarBatchProduction.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'indexBatchProduction' %}">
            Batch Production
        </a>
        <span class="navbar-text " style="position: absolute; right: 45%;">
            {% load i18n %}
            {% language 'id' %}
            {% now "l, d/m/Y H:i" %} WIB
            {% endlanguage %}</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                </li>
                {% if user.get_full_name == None %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/login" title="">Log in</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.get_full_name }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'indexBatchProduction' %}">Home</a></li>
                        <li><a class="dropdown-item" href="{% url 'mesinBatchProduction' %}">Data Mesin</a></li>
                        <li><a class="dropdown-item" href="{% url 'produk:index' %}">Data Produk</a></li>
                        <li><a class="dropdown-item" href="{% url 'produksiBatchProduction' %}">Data Produksi</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="/">Halaman Utama</a></li>
                        <li><a class="dropdown-item" href="/logout">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/snippets/navbar_anonymous.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url "index" %}">
    ADiMS
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

templates/snippets/scriptsBatchProduction.html
{% load static %}

<script src="{% static 'vendor/popper/popperBatchProduction.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/jquery/jqueryBatchProduction.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/bootstrap/bootstrapBatchProduction.js' %}" type="text/javascript"></script>

templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

templates/snippets/stylesBatchProduction.html
{% load static %}

<link href="{% static 'vendor/bootstrap/bootstrapBatchProduction.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'vendor/bootstrap/fontsBatchProduction/bootstrap_icons.css' %}">