SistemPenjadwalan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import viewsBatchProduction

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls','users')),
    path('liniProduksi/', include('liniProduksi.urls','liniProduksi')),
    path('produk/', include('produk.urls','produk')),
    path('jadwal/', include('jadwal.urls','jadwal')),
    path('engineeringOrder/', include('engineeringOrder.urls','engineeringOrder')),
    path('contributor/',views.contributor, name='contributor'),
    path('home/',views.home, name='home'),
    path('', views.index, name='index'),
    path('batch/about/', viewsBatchProduction.about, name='about'),
    path('batch/about/&', viewsBatchProduction.dz, name='dz'),
    path('login/', viewsBatchProduction.loginview, name='login'),
    path('logout/', viewsBatchProduction.logoutview, name='logout'),
    path('plant/', viewsBatchProduction.plant, name='plant'),
    path('batch/', include('BatchProduction.urls'), name='batch'),
    path('<slug:instance>/', viewsBatchProduction.notfound, name='404'),
    # path('', viewsBatchProduction.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jadwal/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'jadwal'

urlpatterns = [
    path('belumKonfirmasi/<str:idStasiunKerjaInput>/', views.belumKonfirmasi_SK, name='belumKonfirmasi_SK'),
    path('belumKonfirmasi/', views.belumKonfirmasi, name='belumKonfirmasi'),
    path('sudahKonfirmasi/<str:idStasiunKerjaInput>/', views.sudahKonfirmasi_SK, name='sudahKonfirmasi_SK'),
    path('sudahKonfirmasi/', views.sudahKonfirmasi, name='sudahKonfirmasi'),
    path('konfirmasi/<str:konfirmasi_id>', views.newKonfirmasi, name='konfirmasi'),
    path('jadwalTersedia/', views.jadwalTersedia, name='jadwalTersedia'),
    path('permintaanMaterial/<str:pm_id>', views.permintaanMaterial, name='permintaanMaterial'),
    path('<str:idStasiunKerjaInput>/', views.index_SK, name='index_SK'),
    path('', views.index, name='index'),
]

liniProduksi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views, viewsStasiunKerja, viewsStasiunKerjaDetail, viewsMaterial, viewsProses, viewsPeralatanProduksi, viewsOperator, viewsLiniProduksi_harian, viewsPengirimanMaterial, viewsGangguan
app_name = 'liniProduksi'

urlpatterns = [
    path('gangguanStasiunKerja/gangguanSelesai/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanSelesai, name='gangguanSelesai'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanForm, name='gangguanForm'),
    path('gangguanStasiunKerja/liniProduksiTerhenti/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.liniProduksiTerhenti, name='liniProduksiTerhenti'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>', viewsGangguan.indikasiMasalah, name='indikasiMasalah'),
    path('gangguanStasiunKerja/<str:idStasiunKerjaInput>', viewsGangguan.gangguanStasiunKerja, name='gangguanSK'),
    path('gangguanStasiunKerja/semua/', viewsGangguan.gangguan_semua, name='gangguanSemua'),
    path('gangguanStasiunKerja/', viewsGangguan.gangguan, name='gangguan'),
    path('updateMaterial/<str:update_id>', viewsMaterial.updateMaterial, name='updateMaterial'),
    path('deleteMaterial/<str:delete_id>', viewsMaterial.deleteMaterial, name='deleteMaterial'),
    path('updateStasiunKerja/<str:update_id>', viewsStasiunKerja.updateStasiunKerja, name='updateStasiunKerja'),
    path('deleteStasiunKerja/<str:delete_id>', viewsStasiunKerja.deleteStasiunKerja, name='deleteStasiunKerja'),
    path('updateLiniProduksi/<str:update_id>', views.updateLiniProduksi, name='updateLiniProduksi'),
    path('deleteLiniProduksi/<str:delete_id>', views.deleteLiniProduksi, name='deleteLiniProduksi'),
    path('updateProses/<str:update_id>', viewsProses.updateProses, name='updateProses'),
    path('deleteProses/<str:delete_id>', viewsProses.deleteProses, name='deleteProses'),
    path('updatePeralatanProduksi/<str:update_id>', viewsPeralatanProduksi.updatePeralatanProduksi, name='updatePeralatanProduksi'),
    path('deletePeralatanProduksi/<str:delete_id>', viewsPeralatanProduksi.deletePeralatanProduksi, name='deletePeralatanProduksi'),
    path('updateOperator/<str:update_id>', viewsOperator.updateOperator, name='updateOperator'),
    path('deleteOperator/<str:delete_id>', viewsOperator.deleteOperator, name='deleteOperator'),
    path('newProses/', viewsProses.newProses, name='newProses'),
    path('newPeralatanProduksi/', viewsPeralatanProduksi.newPeralatanProduksi, name='newPeralatanProduksi'),
    path('newKebutuhanMaterial/', viewsMaterial.newMaterial, name='newKebutuhanMaterial'),
    path('newLiniProduksi/', views.newLiniProduksi, name='newLiniProduksi'),
    path('newStasiunKerja/',viewsStasiunKerja.newStasiunKerja, name='newStasiunKerja'),
    path('newOperator/',viewsOperator.newOperator, name='newOperator'),
    path('newPengirimanMaterial/',viewsPengirimanMaterial.newPengirimanMaterial, name='newPengirimanMaterial'),
    path('updatePengirimanMaterial/<str:update_id>', viewsPengirimanMaterial.updatePengirimanMaterial,
         name='updatePengirimanMaterial'),
    path('deletePengirimanMaterial/<str:delete_id>', viewsPengirimanMaterial.deletePengirimanMaterial,
         name='deletePengirimanMaterial'),
    path('updateTargetHarian/<str:update_id>', viewsLiniProduksi_harian.updateTargetHarian, name='updateTargetHarian'),
    path('deleteTargetHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetHarian, name='deleteTargetHarian'),
    path('produksiHarian/newTargetHarian/<str:produksiHarianInput>',viewsLiniProduksi_harian.newTargetHarian, name='newTargetHarian'),
    path('produksiHarian/newWaktuIstirahat/<str:produksiHarianInput>',viewsLiniProduksi_harian.newWaktuIstirahat, name='newWaktuIstirahat'),
    path('updateWaktuIstirahat/<str:update_id>', viewsLiniProduksi_harian.updateWaktuIstirahat, name='updateWaktuIstirahat'),
    path('deleteWaktuIstirahat/<str:delete_id>', viewsLiniProduksi_harian.deleteWaktuIstirahat, name='deleteWaktuIstirahat'),
    path('updateTargetTahunan/<str:update_id>', viewsLiniProduksi_harian.updateTargetTahunan, name='updateTargetTahunan'),
    path('deleteTargetTahunan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetTahunan, name='deleteTargetTahunan'),
    path('newTargetTahunan/',viewsLiniProduksi_harian.newTargetTahunan, name='newTargetTahunan'),
    path('updateTargetBulanan/<str:update_id>', viewsLiniProduksi_harian.updateTargetBulanan, name='updateTargetBulanan'),
    path('deleteTargetBulanan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetBulanan, name='deleteTargetBulanan'),
    path('newTargetBulanan/',viewsLiniProduksi_harian.newTargetBulanan, name='newTargetBulanan'),
    path('updateTargetMingguan/<str:update_id>', viewsLiniProduksi_harian.updateTargetMingguan, name='updateTargetMingguan'),
    path('deleteTargetMingguan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetMingguan, name='deleteTargetMingguan'),
    path('newTargetMingguan/',viewsLiniProduksi_harian.newTargetMingguan, name='newTargetMingguan'),
    path('newHariLibur/',viewsLiniProduksi_harian.hariLibur, name='newHariLibur'),
    path('newIstirahatNormal/',viewsLiniProduksi_harian.newWaktuIstirahatNormal, name='newIstirahatNormal'),
    path('newProduksiHarian/',viewsLiniProduksi_harian.newProduksiHarian, name='newProduksiHarian'),
    path('updateProduksiHarian/<str:update_id>', viewsLiniProduksi_harian.updateProduksiHarian, name='updateProduksiHarian'),
    path('deleteProduksiHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteProduksiHarian, name='deleteProduksiHarian'),
    path('<str:idLiniProduksiInput>/<str:idStasiunKerjaInput>/', viewsStasiunKerjaDetail.stasiunKerjaDetail, name='stasiunKerjaDetail'),
    path('produksiTahunan/', viewsLiniProduksi_harian.tahunan, name='tahunan'),
    path('produksiBulanan/', viewsLiniProduksi_harian.bulanan, name='bulanan'),
    path('produksiMingguan/', viewsLiniProduksi_harian.mingguan, name='mingguan'),
    path('produksiHarian/', viewsLiniProduksi_harian.harian, name='harian'),
    path('produksi/', viewsLiniProduksi_harian.produksiHarian, name='produksiHarian'),
    path('tambahCapaianProduksi/<str:id>', viewsLiniProduksi_harian.tambahCapaian, name='tambahCapaian'),
    path('<str:idLiniProduksiInput>/', viewsStasiunKerja.stasiunKerja, name='stasiunKerja'),
    path('', views.index, name='index'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views
app_name = 'users'

urlpatterns = [
    path('', views.registerView, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

liniProduksi/views.py
from django.shortcuts import render, redirect

from .models import LiniProduksi
from .forms import LiniProduksiForm
# Create your views here.

# def liniProduksi(request, idBrandInput, idModelInput, idVarianInput):
#     # if request.method=="POST":
#     #     fromdate = request.POST.get('fromdate')
#     #     todate = request.POST.get('todate')
#     #     namaLP = request.POST.get('namaLP')
#     #     searchresult = LiniProduksi.objects.raw('select id,idLiniProduksi,waktuMulaiProduksi,waktuSelesaiProduksi,waktuSiklus,tanggalMulaiProduksi FROM produk_liniproduksi WHERE ((idLiniProduksi = "'+namaLP+'") OR (tanggalMulaiProduksi between "'+fromdate+'" and "'+todate+'")) ')
#     #     context = {
#     #         'Judul': 'Lini Produksi',
#     #         'semua_liniProduksi': searchresult,
#     #
#     #         'css': 'produk/css/styles_table.css',
#     #     }
#     #     return render(request,'produk/index.html', context)
#     # else:
#     model_p = LiniProduksi.objects.filter(brand__id=idBrandInput)
#     varian_p = Varian.objects.filter(id=idVarianInput)
#     liniProduksi = LiniProduksi.objects.filter(varian__id=idVarianInput)
#     context = {
#         'Judul': 'Lini Produksi',
#         'liniProduksi': liniProduksi,
#         'model_p':model_p,
#         'varian_p': varian_p,
#         'css': 'produk/css/styles_table.css',
#     }
#     return render(request,'produk/liniProduksi.html',context)

def index(request):
    liniProduksi = LiniProduksi.objects.all()

    context = {
        'Judul': 'Lini Produksi',
        'liniProduksi': liniProduksi,
        'css': 'produk/css/styles_table.css',
    }
    return render(request, 'liniProduksi/indexV2.html', context)


def newLiniProduksi(request):
    #cara mencocokan antara input dengan data yang telah ada = PostForm(request.POST)
    liniProduksi_form = LiniProduksiForm(request.POST or None)

    # masukin data dari form ke database
    if request.method == 'POST':
        # validasi data
        if liniProduksi_form.is_valid():
            # menyimpan ke database
            liniProduksi_form.save()
            return redirect('liniProduksi:index')
    context = {
        'Judul': 'Tambah Lini Produksi',
        'css': 'produk/css/styles_form.css',
        'liniProduksi_form': liniProduksi_form,
    }
    return render(request,'liniProduksi/newLiniProduksi.html',context)

def deleteLiniProduksi(request, delete_id):
    #cara delete
    LiniProduksi.objects.filter(id=delete_id).delete()
    return redirect('liniProduksi:index')

def updateLiniProduksi(request, update_id):
    #cara edit
    liniProduksi_update = LiniProduksi.objects.get(id=update_id)

    data = {
        'idLiniProduksi': liniProduksi_update.idLiniProduksi,
        'waktuSiklus': liniProduksi_update.waktuSiklus,
        'jumlahStasiunKerja': liniProduksi_update.jumlahStasiunKerja,
    }
    liniProduksi_form = LiniProduksiForm(request.POST or None, initial=data, instance=liniProduksi_update)

    if request.method == 'POST':
        #validasi data
        if liniProduksi_form.is_valid():
            #menyimpan ke database
            liniProduksi_form.save()
            return redirect('liniProduksi:index')

    context = {
        'Judul': 'Update Lini Produksi',
        'liniProduksi_form': liniProduksi_form,
    }

    return render(request,'liniProduksi/newLiniProduksi.html',context)

liniProduksi/templates/liniProduksi/snippets/liniProduksi_delete_modal.html
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Hapus Lini Produksi</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Apakah anda yakin akan menghapus lini produksi ini?
      </div>
      <div class="modal-footer">
          <a class="btn btn-danger" href="{% url "liniProduksi:deleteLiniProduksi" liniProduksi.id %}">Hapus Produk</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

liniProduksi/templates/liniProduksi/snippets/material_delete_modal.html
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Hapus Material</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Apakah anda yakin akan menghapus material ini?
      </div>
      <div class="modal-footer">
          <a class="btn btn-danger" href="{% url "liniProduksi:deleteMaterial" material.id %}">Hapus Material</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

liniProduksi/templates/liniProduksi/snippets/navbar.html
{% load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand ml-5" href="{% url "liniProduksi:index" %}">
    <img alt="Brand" src="{% static "img/icon.png" %}"> Lini Produksi
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "liniProduksi:liniProduksi" %}">Home <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "liniProduksi:liniProduksi" %}">Data Lini Produksi</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "jadwal:index" %}">Jadwal</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Gangguan</a>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url "users:logout" %}">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

liniProduksi/templates/liniProduksi/snippets/proses_nav.html
 <div class="card-header" style="background-color:#d3d9df;">
   <div class="row">
     <div class="col">
       <ul class="nav nav-pills nav-fill" style="background-color:#d3d9df;">
      <li class="nav-item">
        <a class="nav-link active" href="" id="proses-tab" data-toggle="tab" role="tab" aria-controls="proses" aria-selected="false">Proses</a>
      </li>
    </ul>
     </div>
     <div class="col">
       <ul class="nav nav-pills nav-fill" role="tablist" style="background-color:#d3d9df;">
      <li class="nav-item">
        <a class="nav-link" id="operator-tab" data-toggle="tab" href="#operator" role="tab" aria-controls="operator" aria-selected="true">Operator</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="peralatanProduksi-tab" data-toggle="tab" href="#peralatanProduksi" role="tab" aria-controls="peralatanProduksi" aria-selected="false">Peralatan Produksi</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="kebutuhanMaterial-tab" data-toggle="tab" href="#kebutuhanMaterial" role="tab" aria-controls="kebutuhanMaterial" aria-selected="false">Kebutuhan Material</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pengirimanMaterial-tab" data-toggle="tab" href="#pengirimanMaterial" role="tab" aria-controls="pengirimanMaterial" aria-selected="false">Informasi Pengiriman Material</a>
      </li>
    </ul>
     </div>
   </div>
  </div>

liniProduksi/templates/liniProduksi/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

liniProduksi/templates/liniProduksi/snippets/stasiunKerjaDetail_breadcumb.html
 <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page"><a href="{% url "liniProduksi:index" %}">Home</a></li>
                {% for m in stasiunKerja %}
                <li class="breadcrumb-item" aria-current="page"><a href="{% url "liniProduksi:stasiunKerja" idLiniProduksiInput=m.liniProduksi %}">{{m.liniProduksi.idLiniProduksi}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{m.nomorStasiunKerja}} - {{m.sisiStasiunKerja}}</li>
                {% endfor %}
            </ol>
        </nav>

liniProduksi/templates/liniProduksi/snippets/stasiunKerjaDetail_card_nav.html
 <div class="card-header" style="background-color:#d3d9df;">
    <ul class="nav nav-pills nav-fill" role="tablist" style="background-color:#d3d9df;">
      <li class="nav-item">
        <a class="nav-link active" id="proses-tab" data-toggle="tab" href="#proses" role="tab" aria-controls="proses" aria-selected="false">Proses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="operator-tab" data-toggle="tab" href="#operator" role="tab" aria-controls="operator" aria-selected="true">Operator</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="peralatanProduksi-tab" data-toggle="tab" href="#peralatanProduksi" role="tab" aria-controls="peralatanProduksi" aria-selected="false">Peralatan Produksi</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="kebutuhanMaterial-tab" data-toggle="tab" href="#kebutuhanMaterial" role="tab" aria-controls="kebutuhanMaterial" aria-selected="false">Kebutuhan Material</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pengirimanMaterial-tab" data-toggle="tab" href="#pengirimanMaterial" role="tab" aria-controls="pengirimanMaterial" aria-selected="false">Informasi Pengiriman Material</a>
      </li>
    </ul>
  </div>

liniProduksi/templates/liniProduksi/snippets/stasiunKerjaDetail_informasiUmum.html
{% for sk in stasiunKerja %}
<div class="card" style="width:45%;margin:auto;height:185px;">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <h3><u>Informasi Umum</u></h3>
            </div>

            <div class="col-md-6">
<!--                <div class="dropdown" style="float:right;">-->
<!--                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opsi</button>-->
<!--                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">-->
<!--                        <a class="dropdown-item" href="{% url "liniProduksi:deleteStasiunKerja" sk.id %}">Hapus</a>-->
<!--                        <a class="dropdown-item" href="{% url "liniProduksi:updateStasiunKerja" sk.id %}">Edit</a>-->
<!--                    </div>-->
<!--                </div>-->
            </div>
        </div>


        <table class="table table-hover" id="tb2">
            <thead>
            <tr>
                <th>ID Stasiun Kerja</th>
                <td>{{sk.idStasiunKerja}}</td>
            </tr>
            <tr>
                <th>Nomor - Sisi Stasiun Kerja</th>
                <td>{{sk.nomorStasiunKerja}} - {{sk.sisiStasiunKerja}}</td>
            </tr>
            {% endfor %}
            </thead>
        </table>
    </div>
</div>

liniProduksi/templates/liniProduksi/snippets/stasiunKerja_delete_modal.html
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi Hapus Stasiun Kerja</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Apakah anda yakin akan menghapus stasiun kerja ini?
      </div>
      <div class="modal-footer">
          <a class="btn btn-danger" href="{% url "liniProduksi:deleteStasiunKerja" stasiunKerja.id %}">Hapus Stasiun Kerja</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

liniProduksi/templates/liniProduksi/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">